### ISSUE TITLE
--remote option?

### ISSUE THREAD

**Issue by julienma** [SebastianSzturo/dokku-cli#14]
Hey,
I'm trying to use the `--remote` option of dokku-cli, but can't seem to understand how it works.
Is it supposed to be an option to force the git remote name (instead of using the default `dokku`)?

In my local git repo (published to my dokku server), I tried:

```
dokku --remote=dev config
```

Output is:

```
Usage:
  dokku config

Options:
  [--remote=REMOTE]

Display the app's environment variables
```

And nothing happens (no output) if I try:

```
dokku config --remote=dev
```

---

My local git remote is

```
git remote -v
dev ssh://dokku@domain.com:2000/my-app (fetch)
dev ssh://dokku@domain.com:2000/my-app (push)
```

And when logging directly on my dokku box:

```
dokku config my-app
=====> my-app config vars
DOKKU_APP_RESTORE:     1
DOKKU_DOCKERFILE_PORT: 5000
DOKKU_NGINX_PORT:      80
```

**Comment by julienma** [comment]
Also: I created the git remote manually (`git remote add dev ssh://dokku@domain.com:2000/my-app`).
Is there any dokku's `--remote` option I'm not aware of, to use when creating an app?

**Comment by SebastianSzturo** [comment]
Sorry about that. I broke the --remote flag in `0.3.0`. I've just pushed a fix!

This is the correct way to use it and should work fine with `0.3.1`

```
dokku config --remote=dev
```

EDIT: I've also fixed the example in the `README.md` and hope everything works fine for you now.

**Comment by julienma** [comment]
Works great now, thanks :+1:

**Comment by idrozd** [comment]
worked with config, doesn't work with **run rails c** )

**Comment by beydogan** [comment]
same as @idrozd, it works with config but doesn't effect **dokku run** commands
