### ISSUE TITLE
Adding remotes for dokku

### ISSUE THREAD

**Issue by SnezanaDichevska** [SebastianSzturo/dokku-cli#15]
I was trying to add multiple remotes for my app following your instructions:
You can use the global option --remote to run commands on a different server/app from a remote branch. For more details see heroku's guide for multiple environments for an app.

`dokku run rails c --remote=staging`
`dokku config --remote=staging`

However the --remote option doesn't work for me. 
I also noticed that in the heroku's guide they add remotes like this: 
`heroku create --remote staging`,
but dokku-cli doesn't seem to have this command. **Any help?**

**Comment by knjcode** [comment]
The `--remote` global option is currently not working in run, open, logs commands.
https://github.com/SebastianSzturo/dokku-cli/pull/16 fixes this.

You can use remote option in the run command after https://github.com/SebastianSzturo/dokku-cli/pull/16 merged and released.
