### ISSUE TITLE
Managing multiple Apps in a single repo

### ISSUE THREAD

**Issue by eddiejaoude** [SebastianSzturo/dokku-cli#4]
```
dokku command app
```

**Comment by SebastianSzturo** [comment]
You mean one repository that has multiple dokku remotes?

**Comment by eddiejaoude** [comment]
Yes. Same as having multiple remotes on heroku https://devcenter.heroku.com/articles/multiple-environments

**Comment by SebastianSzturo** [comment]
Thats a great idea. I will try to put something together today :)

**Comment by eddiejaoude** [comment]
Great, thanks!

**Comment by SebastianSzturo** [comment]
Took a bit longer, but its now in the v0.2.0 release and on RubyGems :)

**Comment by eddiejaoude** [comment]
Great :+1:
