### ISSUE TITLE
dokku domains:add crashes when used with --remote option

### ISSUE THREAD

**Issue by noodny** [SebastianSzturo/dokku-cli#5]
dokku domains:add test --remote=beta
/Library/Ruby/Gems/2.0.0/gems/dokku-cli-0.2.0/lib/dokku_cli/domains.rb:10:in `domains_add': wrong number of arguments (2 for 1) (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/dokku-cli-0.2.0/lib/dokku_cli.rb:67:in`method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:126:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/dokku-cli-0.2.0/bin/dokku:5:in`<top (required)>'
    from /usr/bin/dokku:23:in `load'
    from /usr/bin/dokku:23:in`<main>'

**Comment by noodny** [comment]
this generally crashes on multiple commands, perhaps consider moving the parameter in front of dokku comand? like `dokku --remote=beta domains:add test`

**Comment by SebastianSzturo** [comment]
It seams like thor's `class_option` ([dokku_cli.rb#L11](https://github.com/SebastianSzturo/dokku-cli/blob/master/lib/dokku_cli.rb#L11)) is not filtering out the remote argument before it goes into the method. I will look into it!

**Comment by SebastianSzturo** [comment]
Fixed with #6. New Release is on the way!
