### ISSUE TITLE
dokku on different port other than 22

### ISSUE THREAD

**Issue by guatedude2** [SebastianSzturo/dokku-cli#9]
I use ssh on 2202 on my dokku server but dokku-cli doesn't allow me to change the port. would be nice to have a way to set configure this. So I have to change the port every time i want to deploy a new container.

**Comment by SebastianSzturo** [comment]
I am thinking about adding a way to configure `dokku-cli` with a `DOKKU`` file. 
I will add an option for the port too. Thanks for the suggestion!

**Comment by guatedude2** [comment]
Awesome! Thank you

**Comment by julienma** [comment]
I'm also interested; any way to help with that?

FYI, here's the syntax to add a dokku remote using a different port:

```
git remote add dokku ssh://dokku@domain.com:1337/my-app-subdomain
# instead of: git remote add dokku dokku@domain.com:my-app-subdomain
```

**Comment by SebastianSzturo** [comment]
@julienma Thats a really great idea to just use the ssh prefix and add the port through the remote url! 

We would just need to add another regex to check which url schema we are dealing with and to filter out the port. PRs are welcome! :heart: 

I am bit busy right now, but I can try to look into adding this in the next few weeks.

**Comment by julienma** [comment]
I'm willing to help on that, even though I'm not a dev.

I'd need some guidance though.
How would you plan to let the user specify the SSH port (interactive or he has to edit a config file)?

And what do you mean with "add another regex to check which url schema we are dealing with "? Is there already an existing regex? What is it for?

**Comment by SebastianSzturo** [comment]
Should be solved now. Thanks again @julienma for the simple solution.

I will release a new 0.3 version with a few new features today.

**Comment by julienma** [comment]
\o/
Great, thanks!
